apiVersion: v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace : dev
  labels:
   app : myapp
   type : front-end
spec:
 - template :
   metadata:
    name : myapp-pod
    labels : 
      app : myapp
      type : front-end
   spec:
     containers:
     - name : reactapplatest
       image : azmytc/zimatc:latest
       ports :
       containerPort : 3000
       
replicas: 2
selector :
 matchLabels:
  type : react-app