apiVersion: v1
kind: Service
metadata:
  name: react-appservice
  labels:
    app: react-service
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    nodePort: 5000
    protocol: TCP
  selector:
    app: react-service